# Generated by Django 5.2.4 on 2025-11-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='extra_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
